/*
Tailscale API

Tailscale API spec

API version: 1.0
Contact: hello@opal.dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package opal

import (
	"encoding/json"
)

// SSHRule struct for SSHRule
type SSHRule struct {
	Action *string `json:"action,omitempty"`
	Src []string `json:"src,omitempty"`
	Dst []string `json:"dst,omitempty"`
	Users []string `json:"users,omitempty"`
}

// NewSSHRule instantiates a new SSHRule object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSSHRule() *SSHRule {
	this := SSHRule{}
	return &this
}

// NewSSHRuleWithDefaults instantiates a new SSHRule object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSSHRuleWithDefaults() *SSHRule {
	this := SSHRule{}
	return &this
}

// GetAction returns the Action field value if set, zero value otherwise.
func (o *SSHRule) GetAction() string {
	if o == nil || o.Action == nil {
		var ret string
		return ret
	}
	return *o.Action
}

// GetActionOk returns a tuple with the Action field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SSHRule) GetActionOk() (*string, bool) {
	if o == nil || o.Action == nil {
		return nil, false
	}
	return o.Action, true
}

// HasAction returns a boolean if a field has been set.
func (o *SSHRule) HasAction() bool {
	if o != nil && o.Action != nil {
		return true
	}

	return false
}

// SetAction gets a reference to the given string and assigns it to the Action field.
func (o *SSHRule) SetAction(v string) {
	o.Action = &v
}

// GetSrc returns the Src field value if set, zero value otherwise.
func (o *SSHRule) GetSrc() []string {
	if o == nil || o.Src == nil {
		var ret []string
		return ret
	}
	return o.Src
}

// GetSrcOk returns a tuple with the Src field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SSHRule) GetSrcOk() ([]string, bool) {
	if o == nil || o.Src == nil {
		return nil, false
	}
	return o.Src, true
}

// HasSrc returns a boolean if a field has been set.
func (o *SSHRule) HasSrc() bool {
	if o != nil && o.Src != nil {
		return true
	}

	return false
}

// SetSrc gets a reference to the given []string and assigns it to the Src field.
func (o *SSHRule) SetSrc(v []string) {
	o.Src = v
}

// GetDst returns the Dst field value if set, zero value otherwise.
func (o *SSHRule) GetDst() []string {
	if o == nil || o.Dst == nil {
		var ret []string
		return ret
	}
	return o.Dst
}

// GetDstOk returns a tuple with the Dst field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SSHRule) GetDstOk() ([]string, bool) {
	if o == nil || o.Dst == nil {
		return nil, false
	}
	return o.Dst, true
}

// HasDst returns a boolean if a field has been set.
func (o *SSHRule) HasDst() bool {
	if o != nil && o.Dst != nil {
		return true
	}

	return false
}

// SetDst gets a reference to the given []string and assigns it to the Dst field.
func (o *SSHRule) SetDst(v []string) {
	o.Dst = v
}

// GetUsers returns the Users field value if set, zero value otherwise.
func (o *SSHRule) GetUsers() []string {
	if o == nil || o.Users == nil {
		var ret []string
		return ret
	}
	return o.Users
}

// GetUsersOk returns a tuple with the Users field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SSHRule) GetUsersOk() ([]string, bool) {
	if o == nil || o.Users == nil {
		return nil, false
	}
	return o.Users, true
}

// HasUsers returns a boolean if a field has been set.
func (o *SSHRule) HasUsers() bool {
	if o != nil && o.Users != nil {
		return true
	}

	return false
}

// SetUsers gets a reference to the given []string and assigns it to the Users field.
func (o *SSHRule) SetUsers(v []string) {
	o.Users = v
}

func (o SSHRule) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Action != nil {
		toSerialize["action"] = o.Action
	}
	if o.Src != nil {
		toSerialize["src"] = o.Src
	}
	if o.Dst != nil {
		toSerialize["dst"] = o.Dst
	}
	if o.Users != nil {
		toSerialize["users"] = o.Users
	}
	return json.Marshal(toSerialize)
}

type NullableSSHRule struct {
	value *SSHRule
	isSet bool
}

func (v NullableSSHRule) Get() *SSHRule {
	return v.value
}

func (v *NullableSSHRule) Set(val *SSHRule) {
	v.value = val
	v.isSet = true
}

func (v NullableSSHRule) IsSet() bool {
	return v.isSet
}

func (v *NullableSSHRule) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSSHRule(val *SSHRule) *NullableSSHRule {
	return &NullableSSHRule{value: val, isSet: true}
}

func (v NullableSSHRule) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSSHRule) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


