/*
Tailscale API

Tailscale API spec

API version: 1.0
Contact: hello@opal.dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package opal

import (
	"encoding/json"
)

// ACLRule struct for ACLRule
type ACLRule struct {
	Action string `json:"action"`
	Src []string `json:"src"`
	Dst []string `json:"dst"`
}

// NewACLRule instantiates a new ACLRule object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewACLRule(action string, src []string, dst []string) *ACLRule {
	this := ACLRule{}
	this.Action = action
	this.Src = src
	this.Dst = dst
	return &this
}

// NewACLRuleWithDefaults instantiates a new ACLRule object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewACLRuleWithDefaults() *ACLRule {
	this := ACLRule{}
	return &this
}

// GetAction returns the Action field value
func (o *ACLRule) GetAction() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Action
}

// GetActionOk returns a tuple with the Action field value
// and a boolean to check if the value has been set.
func (o *ACLRule) GetActionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Action, true
}

// SetAction sets field value
func (o *ACLRule) SetAction(v string) {
	o.Action = v
}

// GetSrc returns the Src field value
func (o *ACLRule) GetSrc() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Src
}

// GetSrcOk returns a tuple with the Src field value
// and a boolean to check if the value has been set.
func (o *ACLRule) GetSrcOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Src, true
}

// SetSrc sets field value
func (o *ACLRule) SetSrc(v []string) {
	o.Src = v
}

// GetDst returns the Dst field value
func (o *ACLRule) GetDst() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Dst
}

// GetDstOk returns a tuple with the Dst field value
// and a boolean to check if the value has been set.
func (o *ACLRule) GetDstOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Dst, true
}

// SetDst sets field value
func (o *ACLRule) SetDst(v []string) {
	o.Dst = v
}

func (o ACLRule) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["action"] = o.Action
	}
	if true {
		toSerialize["src"] = o.Src
	}
	if true {
		toSerialize["dst"] = o.Dst
	}
	return json.Marshal(toSerialize)
}

type NullableACLRule struct {
	value *ACLRule
	isSet bool
}

func (v NullableACLRule) Get() *ACLRule {
	return v.value
}

func (v *NullableACLRule) Set(val *ACLRule) {
	v.value = val
	v.isSet = true
}

func (v NullableACLRule) IsSet() bool {
	return v.isSet
}

func (v *NullableACLRule) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableACLRule(val *ACLRule) *NullableACLRule {
	return &NullableACLRule{value: val, isSet: true}
}

func (v NullableACLRule) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableACLRule) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


